# Generated by Django 4.0.3 on 2022-05-19 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('iata', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='IATA')),
                ('name', models.CharField(max_length=255, verbose_name='Название аэропорта')),
            ],
            options={
                'verbose_name': 'Аэропорт',
                'verbose_name_plural': 'Аэропорты',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Категории вещи')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название города')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название цвета')),
                ('color', models.CharField(max_length=9, verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Цвет',
                'verbose_name_plural': 'Цвета',
            },
        ),
        migrations.CreateModel(
            name='DocScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan', models.ImageField(upload_to='', verbose_name='Скан документа')),
            ],
            options={
                'verbose_name': 'Скан документа',
                'verbose_name_plural': 'Сканы документов',
            },
        ),
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Вид вещи')),
            ],
            options={
                'verbose_name': 'Вид',
                'verbose_name_plural': 'Виды',
            },
        ),
        migrations.CreateModel(
            name='LostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата передачи вещей')),
                ('comment', models.CharField(max_length=500, verbose_name='Комментарий')),
                ('tag', models.CharField(max_length=255, verbose_name='Номер бирки')),
                ('status', models.BooleanField(default=False, verbose_name='Передана вещь')),
                ('demanded', models.BooleanField(default=False, verbose_name='Востребована')),
            ],
            options={
                'verbose_name': 'Вещь переданная САБ в камеру хранения',
                'verbose_name_plural': 'Вещи переданные САБ в камеру хранения',
            },
        ),
        migrations.CreateModel(
            name='LuggageStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminal', models.CharField(max_length=255, verbose_name='Буква терминала')),
                ('floor', models.IntegerField(verbose_name='Этаж')),
                ('default', models.BooleanField(default=False, verbose_name='По умолчанию')),
                ('image', models.ImageField(upload_to='LS', verbose_name='Схема расположения камеры хранения')),
            ],
            options={
                'verbose_name': 'Камера хранения',
                'verbose_name_plural': 'Камеры хранения',
            },
        ),
        migrations.CreateModel(
            name='LuggageStorageInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255, verbose_name='Местоположение')),
                ('work_time', models.CharField(max_length=255, verbose_name='Время работы')),
                ('conditions', models.CharField(max_length=255, verbose_name='Условия')),
            ],
            options={
                'verbose_name': 'Информация о камере хранения',
                'verbose_name_plural': 'Информация о камерах хранения',
            },
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='SABItem', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Фотография САБ',
                'verbose_name_plural': 'Фотографии САБ',
            },
        ),
        migrations.CreateModel(
            name='RefundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=300, verbose_name='ФИО')),
                ('series_number', models.CharField(max_length=100, verbose_name='Серия и номер')),
                ('date_get', models.DateField(verbose_name='Дата получения')),
                ('how_get', models.CharField(max_length=255, verbose_name='Кем выдан')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('first_scan', models.ImageField(blank=True, null=True, upload_to='documents/lostitem', verbose_name='Певый скан')),
                ('second_scan', models.ImageField(blank=True, null=True, upload_to='documents/lostitem', verbose_name='Второй скан')),
                ('scan_refund', models.ImageField(blank=True, null=True, upload_to='documents/lostitem', verbose_name='Заявление на возврат')),
                ('scan_receipt', models.ImageField(blank=True, null=True, upload_to='documents/lostitem', verbose_name='Расписка за получение')),
                ('refund_date', models.DateTimeField(verbose_name='Дата возврата вещи')),
            ],
            options={
                'verbose_name': 'Возвращеная вещь',
                'verbose_name_plural': 'Возвращенные вещи',
            },
        ),
        migrations.CreateModel(
            name='RefundSAB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('close_date', models.DateField()),
                ('broadcast_date', models.DateField()),
            ],
            options={
                'verbose_name': 'Возвращеная вещь САБ',
                'verbose_name_plural': 'Возвращенные вещи САБ',
            },
        ),
        migrations.CreateModel(
            name='SABItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата и время находки')),
                ('act', models.BooleanField(default=False, verbose_name='Акт осмотра')),
                ('comment', models.CharField(max_length=500, verbose_name='Комментарий')),
                ('status', models.BooleanField(default=False, verbose_name='Передана на склад?')),
            ],
            options={
                'verbose_name': 'Найденные вещи сотруднком САБ',
                'verbose_name_plural': 'Найденные вещи сотрудником САБ',
            },
        ),
        migrations.CreateModel(
            name='TimeForUnclaimed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta_time', models.IntegerField(verbose_name='Срок хранения вещи')),
                ('date_create', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Время хранения вещи',
                'verbose_name_plural': 'Время хранения вещей',
            },
        ),
        migrations.CreateModel(
            name='U_LS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата связи')),
            ],
            options={
                'verbose_name': 'Таблица связи сотрудника и камеры хранения',
                'verbose_name_plural': 'Таблицы связи сотрудника и камеры хранения',
            },
        ),
        migrations.CreateModel(
            name='WorkerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя и фамилия сотрудника')),
                ('access_mobile', models.BooleanField(default=False, verbose_name='Доступ к телефону')),
            ],
            options={
                'verbose_name': 'Информация о сотруднике',
                'verbose_name_plural': 'Информация о сотрудниках',
            },
        ),
    ]
