# Generated by Django 4.0.3 on 2022-05-19 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bag_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Данные сотрудника'),
        ),
        migrations.AddField(
            model_name='u_ls',
            name='ls',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bag_admin.luggagestorage', verbose_name='Камера хранения'),
        ),
        migrations.AddField(
            model_name='u_ls',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Данные сотрудника'),
        ),
        migrations.AddField(
            model_name='timeforunclaimed',
            name='airport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time', to='bag_admin.airport'),
        ),
        migrations.AddField(
            model_name='sabitem',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bag_admin.luggagestorage', verbose_name='Место находки'),
        ),
        migrations.AddField(
            model_name='sabitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник САБ'),
        ),
        migrations.AddField(
            model_name='refundsab',
            name='lost_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bag_admin.lostitem', verbose_name='Потерянная вещь'),
        ),
        migrations.AddField(
            model_name='refundsab',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Выдана сотрудником'),
        ),
        migrations.AddField(
            model_name='refunditem',
            name='lost_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bag_admin.lostitem', verbose_name='Потерянная вещь'),
        ),
        migrations.AddField(
            model_name='refunditem',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Выдана сотрудником'),
        ),
        migrations.AddField(
            model_name='photos',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='bag_admin.sabitem'),
        ),
        migrations.AddField(
            model_name='luggagestorageinfo',
            name='ls',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='bag_admin.luggagestorage', verbose_name='Камера хранения'),
        ),
        migrations.AddField(
            model_name='luggagestorage',
            name='airport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bag_admin.airport', verbose_name='Аэропорт'),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bag_admin.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bag_admin.color', verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='kh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bag_admin.luggagestorage', verbose_name='Камера хранения'),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='kind',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bag_admin.kind', verbose_name='Вид'),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='sab_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bag_admin.sabitem', verbose_name='Вещи найденные САБ'),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник принявший вещи'),
        ),
        migrations.AddField(
            model_name='kind',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bag_admin.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='docscan',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docscan', to='bag_admin.refundsab'),
        ),
        migrations.AddField(
            model_name='airport',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bag_admin.city', verbose_name='Город, в котором находится аэропорт'),
        ),
    ]
