# Generated by Django 4.0.3 on 2022-05-30 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bag_admin', '0003_placeluggagestorage'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='airport',
            name='lon',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9, verbose_name='Долгота'),
        ),
    ]
