# Generated by Django 4.0.3 on 2022-06-08 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bag_admin', '0004_airport_lat_airport_lon'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='airport'),
        ),
    ]
