# Generated by Django 4.0.3 on 2022-06-08 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bag_admin', '0005_airport_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='luggagestorage',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='LS_photo', verbose_name='Фотография камеры хранения'),
        ),
    ]
