# Generated by Django 4.0.3 on 2022-05-19 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('keepit_admin', '0001_initial'),
        ('lostitems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='u_a',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='record',
            name='cell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keepit_admin.cell', verbose_name='Ячейка'),
        ),
        migrations.AddField(
            model_name='record',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Кто совершил действие'),
        ),
        migrations.AddField(
            model_name='partner',
            name='brend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keepit_admin.brend', verbose_name='Бренд'),
        ),
        migrations.AddField(
            model_name='item',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь вещи'),
        ),
        migrations.AddField(
            model_name='history',
            name='records',
            field=models.ManyToManyField(to='keepit_admin.record', verbose_name='Записи'),
        ),
        migrations.AddField(
            model_name='deliveryitem',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lostitems.address', verbose_name='Адре доставки'),
        ),
        migrations.AddField(
            model_name='deliveryitem',
            name='items',
            field=models.ManyToManyField(related_name='delivery_item', to='keepit_admin.item', verbose_name='Доставляеме вещи'),
        ),
        migrations.AddField(
            model_name='deliveryitem',
            name='type_delibery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keepit_admin.company', verbose_name='Компания доставки'),
        ),
        migrations.AddField(
            model_name='deliveryitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='cell',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='keepit_admin.item', verbose_name='Вещь в ячейке'),
        ),
        migrations.AddField(
            model_name='automat',
            name='cells',
            field=models.ManyToManyField(related_name='automat', to='keepit_admin.cell', verbose_name='Ячейки'),
        ),
        migrations.AddField(
            model_name='automat',
            name='history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automat', to='keepit_admin.history', verbose_name='История автомата'),
        ),
    ]
