# Generated by Django 4.0.3 on 2022-05-20 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kh_mobile', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='luggage',
            name='kind_luggage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kh_mobile.kindluggage', verbose_name='Вид вещи'),
        ),
    ]
