# Generated by Django 4.0.3 on 2022-05-20 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kh_mobile', '0003_luggage_kind_luggage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photo',
            new_name='PhotoLuggage',
        ),
    ]
