# Generated by Django 4.0.3 on 2022-05-21 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kh_mobile', '0004_rename_photo_photoluggage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='luggage',
            name='date',
        ),
        migrations.RemoveField(
            model_name='luggage',
            name='price',
        ),
        migrations.RemoveField(
            model_name='luggage',
            name='sale',
        ),
        migrations.AddField(
            model_name='luggage',
            name='date_create',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата создания багажа'),
        ),
        migrations.AddField(
            model_name='luggage',
            name='date_send',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата сдачи багажа'),
        ),
        migrations.AddField(
            model_name='luggage',
            name='date_take',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата получения багажа'),
        ),
        migrations.AddField(
            model_name='luggage',
            name='price_day_storage',
            field=models.IntegerField(blank=True, null=True, verbose_name='Стоимость хранения'),
        ),
        migrations.AddField(
            model_name='luggage',
            name='price_per_day',
            field=models.IntegerField(blank=True, null=True, verbose_name='Стоимость 1 дня хранения'),
        ),
        migrations.AddField(
            model_name='luggage',
            name='price_storage',
            field=models.IntegerField(blank=True, null=True, verbose_name='Стоимость сдачи'),
        ),
        migrations.AddField(
            model_name='luggage',
            name='sale_day_storage',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество списанных баллов mileonair за хранение багажа'),
        ),
        migrations.AddField(
            model_name='luggage',
            name='sale_storage',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество списанных баллов mileonair за сдачу багажа'),
        ),
        migrations.AlterField(
            model_name='luggage',
            name='total_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Итоговая стоимость'),
        ),
        migrations.AlterField(
            model_name='photoluggage',
            name='luggage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='kh_mobile.luggage', verbose_name='Багаж'),
        ),
    ]
