# Generated by Django 4.0.3 on 2022-05-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kh_mobile', '0005_remove_luggage_date_remove_luggage_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='luggage',
            name='date_create',
            field=models.DateTimeField(verbose_name='Дата создания багажа'),
        ),
        migrations.AlterField(
            model_name='luggage',
            name='price_per_day',
            field=models.IntegerField(verbose_name='Стоимость 1 дня хранения'),
        ),
        migrations.AlterField(
            model_name='luggage',
            name='price_storage',
            field=models.IntegerField(verbose_name='Стоимость сдачи'),
        ),
        migrations.AlterField(
            model_name='luggage',
            name='sale_storage',
            field=models.IntegerField(verbose_name='Количество списанных баллов mileonair за сдачу багажа'),
        ),
    ]
