# Generated by Django 4.0.3 on 2022-05-21 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kh_mobile', '0006_alter_luggage_date_create_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='luggage',
            name='issued_staff',
            field=models.BooleanField(default=False, verbose_name='Оформлено сотрудником'),
        ),
    ]
