# Generated by Django 4.0.3 on 2022-06-08 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kh_mobile', '0008_luggage_day_storage_luggage_place_ls'),
    ]

    operations = [
        migrations.AddField(
            model_name='codecity',
            name='iso2',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='codecity',
            name='iso3',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
